"""add tag

Revision ID: 37e51d7dcbe5
Revises: 09bc7a8a07e1
Create Date: 2026-01-27 15:44:49.619072

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa




# revision identifiers, used by Alembic.
revision: str = '37e51d7dcbe5'
down_revision: Union[str, Sequence[str], None] = '09bc7a8a07e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Enum('EXPRESS', 'STANDARD', 'FRAGILE', 'HEAVY', 'INTERNATIONAL', 'DOMESTIC', 'TEMPERATURE_CONTROLLED', 'GIFT', 'RETURN', 'DOCUMENTS', name='tagname'), nullable=False),
    sa.Column('instruction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipment_tag_link',
    sa.Column('shipment_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('shipment_id', 'tag_id')
    )
    # ### end Alembic commands ###

    ### Add tag entries in the database ###
    op.execute(
        sa.text(
            """
            INSERT INTO tag (id, name, instruction) VALUES 
            (gen_random_uuid(), 'EXPRESS', 'Express delivery handling required'),
            (gen_random_uuid(), 'STANDARD', 'Standard delivery handling required'),
            (gen_random_uuid(), 'FRAGILE', 'Fragile items - handle with care'),
            (gen_random_uuid(), 'HEAVY', 'Heavy item - use appropriate equipment'),
            (gen_random_uuid(), 'INTERNATIONAL', 'International shipping - check customs requirements'),
            (gen_random_uuid(), 'DOMESTIC', 'Domestic shipping handling required'),
            (gen_random_uuid(), 'TEMPERATURE_CONTROLLED', 'Temperature controlled - maintain cold chain'),
            (gen_random_uuid(), 'GIFT', 'Gift item - handle with care'),
            (gen_random_uuid(), 'RETURN', 'Return shipment - process accordingly'),
            (gen_random_uuid(), 'DOCUMENTS', 'Document shipment - keep dry and flat')
            """
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipment_tag_link')
    op.drop_table('tag')
    # ### end Alembic commands ###
